### ISSUE TITLE
Why do we need to set `accessible: true`?

### ISSUE THREAD

**Issue by diehardest** [isnifer/react-native-testid#3]

**Comment by cybergrind** [comment]
Because you cannot set testID on android. https://github.com/facebook/react-native/issues/7135

**Comment by diehardest** [comment]
@cybergrind, thank you for the fast response. 

But I asked about `accessible` property. Look at this line
`    { accessible: true, accessibilityLabel: id } :
`

Why do we need to set `accessible: true`? Is simple `accessibilityLabel: id` not enough?

**Comment by cybergrind** [comment]
@diehardest, it was the only way to have it working on Android (battle-tested empyrical solution). If you find another solution feel free to write an update =)
